[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = default_8MB.csv
board_build.filesystem = spiffs
monitor_speed = 115200
lib_ldf_mode = chain+

; Local project libraries are resolved from lib/ through these includes:
; SI470X: <SI470X.h>, TFT_eSPI: <TFT_eSPI.h>, TJpg_Decoder: <TJpg_Decoder.h>, IRremote: <IRremote.hpp>

build_flags =
    -DUSER_SETUP_LOADED
    -DILI9341_DRIVER
    -DTFT_MISO=-1
    -DTFT_MOSI=41
    -DTFT_SCLK=40
    -DTFT_CS=1
    -DTFT_DC=42
    -DTFT_RST=2
    -DLOAD_GLCD
    -DLOAD_FONT2
    -DLOAD_FONT4
    -DLOAD_FONT7


