[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = default_8MB.csv
monitor_speed = 115200

build_flags =
    -DUSER_SETUP_LOADED
    -DILI9341_DRIVER
    -DTFT_MISO=-1
    -DTFT_MOSI=41
    -DTFT_SCLK=40
    -DTFT_CS=1
    -DTFT_DC=42
    -DTFT_RST=2
    -DLOAD_GLCD
    -DLOAD_FONT2
    -DLOAD_FONT4
    -DLOAD_FONT7


lib_deps =
    https://github.com/pu2clr/SI470X.git
    https://github.com/Bodmer/TFT_eSPI.git